baseUrl: https://attilam.com/
title: "Attilam :: WORD :: "
description: "@attilam's Homepage"
author: "@attilam"

destPath: 'public/'

# smol will gather all files from the paths below
routes:
  'content':
    sourcePath: 'content/'
    destPath: '/'
  'assets':
    sourcePath: 'assets/'
    destPath: '/'
  # 'cheatsheets':
  #   sourcePath: '../../../cheatsheets/'
  #   skip:
  #     - '.git/'
  #     - 'README.md'
  #   destPath: 'cheatsheets/'
  #   layout: 'cheatsheet'
  # 'notes':
  #   sourcePath: '/mnt/c/Users/attil/Dropbox/Braindump/Notes/'
  #   destPath: 'notes/'
